<?php

/**
 * Implements hook_ctools_plugin_directory().
 */
function pps_panels_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'panels') {
    return "plugins/$plugin_type";
  }
}

function theme_pps_panels_default_region($vars) {
  $style = !empty($vars['settings']['style']) ? $vars['settings']['style'] : 'neutral';
  $output = '';
  $output .= '<div class="region-style-pps region-style-pps-' . $style . '">';
  $output .= implode(PHP_EOL, $vars['panes']);
  $output .= '</div>';
  return $output;
}

function theme_pps_panels_default_pane($vars) {
  dpm($vars, 'pane');
}