<?php
/**
 * @file
 * Code for the Languages feature.
 */

define('PPS_I18N_LANGUAGE_NEGOTIATION_DOMAIN', 'pps_i18n_domain');

include_once 'pps_i18n.features.inc';

/**
 * Implements hook_panels_pane_content_alter().
 *
 * Make pane titles translatable.
 */
function pps_i18n_panels_pane_content_alter($content, $pane, $args, $context) {
  if ($content->title) {
    $content->title = t($content->title);
  }
  return $content;
}
